version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-local
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server",  "--requirepass", "redis"]
  
  nodejs:
    build:
      context: .
      dockerfile: dockerfile  # Path to your Node.js Dockerfile
    container_name: nodejs-backend
    ports:
      - "3001:3001"  # Adjust to your Node.js port
    depends_on:
      - redis
    env_file:
      - .env

    command: ["npm", "run", "dev"]

volumes:
  redis_data: