apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-openshift-ingress-communication-layer
spec:
  podSelector:
    matchLabels:
      app: communication-layer
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              network.openshift.io/policy-group: ingress
      ports:
        - protocol: TCP
          port: 3030 
  podSelector: {}
  policyTypes:
    - Ingress
